// <auto-generated />
namespace MyTvChannel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Designer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Designer));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280355259_Designer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
